### ISSUE TITLE
upgrade to Sentis 2+ ?

### ISSUE THREAD

**Issue by trackme518** [julienkay/com.doji.sentis-utils#1]
Hi,
first of all - thanks a lot for the work. I am experimenting with your Midas package but I also wanted to try diffusers - which depend on transformers which depend on this utils package. 

However, it is compatible with Sentis 1.6 not 2+ - namely the changes are listed here: 
[upgrade](https://docs.unity3d.com/Packages/com.unity.sentis@2.0/manual/upgrade-guide.html )
I tried to replace TensorFloat with Tensor<float> and the same for int which works fine but I am not sure how to replace the IBackend with graph calls. 

Do you plan to update to new version or are you passed that? 
Thanks for the heads up.

**Comment by julienkay** [comment]
Hey, thanks for reaching out.

you've pointed to the root of the issue: I was relying on Ops/IBackend heavily in all of these repos, thus updating to newer Sentis versions is a bit difficult.
What I've done in the main development branch (master) in the diffusers/transformers/sentis-utils repos is to update to my own [fork of Sentis](https://github.com/julienkay/com.unity.sentis) that's up-to-date with the latest version (2.1.1) and exposes the backend classes again, since they're still used internally.

But none of this is in any released package on OpenUPM yet, so right now your only options are to go with 1.6, or use the latest package versions directly from GitHub and update the dependency to the forked package.

As for future plans: I honestly don't know. Exposing the IBackend classes works for now, but I'd rather not have to fork of course.

**Comment by trackme518** [comment]
Thanks a lot for such a fast response. I totally understand. If I would be working on this, I will drop an update but I can not guarantee it at this point.
